gui:
  theme:
    activeBorderColor:
      - "#8BD3FF"
      - bold
    inactiveBorderColor:
      - "#697080"
    optionsTextColor:
      - "#8BD3FF"
    selectedLineBgColor:
      - "#333B4B"
    defaultFgColor:
      - "#FFFFFF"
