gui:
  theme:
    activeBorderColor:
      - "#8BD3FF"
      - bold
    inactiveBorderColor:
      - "#6D707A"
    optionsTextColor:
      - "#8BD3FF"
    selectedLineBgColor:
      - "#383B44"
    defaultFgColor:
      - "#FFFFFF"
