gui:
  theme:
    activeBorderColor:
      - "#FFB8D1"
      - bold
    inactiveBorderColor:
      - "#6D707A"
    searchingActiveBorderColor:
      - "#8BD3FF"
      - bold
    optionsTextColor:
      - "#8BD3FF"
    selectedLineBgColor:
      - "#383B44"
    cherryPickedCommitFgColor:
      - "#8BD3FF"
    cherryPickedCommitBgColor:
      - "#383B44"
    markedBaseCommitFgColor:
      - "#DDA05C"
    markedBaseCommitBgColor:
      - "#383B44"
    unstagedChangesColor:
      - "#FF8F9A"
    defaultFgColor:
      - "#FFFFFF"
