gui:
  theme:
    activeBorderColor:
      - "#FFB8D1"
      - bold
    inactiveBorderColor:
      - "#697080"
    searchingActiveBorderColor:
      - "#8BD3FF"
      - bold
    optionsTextColor:
      - "#8BD3FF"
    selectedLineBgColor:
      - "#333B4B"
    cherryPickedCommitFgColor:
      - "#8BD3FF"
    cherryPickedCommitBgColor:
      - "#333B4B"
    markedBaseCommitFgColor:
      - "#DDA05C"
    markedBaseCommitBgColor:
      - "#333B4B"
    unstagedChangesColor:
      - "#FF8F9A"
    defaultFgColor:
      - "#FFFFFF"
