format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

palette = "dusk"

[os]
disabled = false
style = "fg:text bg:surface0"

[os.symbols]
Macos = " "
Linux = " "
Windows = " "

[directory]
style = "fg:pink"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"projects" = "󰲋 "

[git_branch]
symbol = ""
style = "fg:sky"
format = "[$symbol$branch ]($style)"

[git_status]
style = "fg:overlay2"
format = "[$all_status$ahead_behind ]($style)"

[nodejs]
symbol = " "
style = "fg:green"
format = "[ $symbol$version ]($style)"

[python]
symbol = " "
style = "fg:yellow"
format = "[ $symbol$version ]($style)"

[rust]
symbol = "󱘗 "
style = "fg:peach"
format = "[ $symbol$version ]($style)"

[golang]
symbol = " "
style = "fg:blue"
format = "[ $symbol$version ]($style)"

[docker_context]
symbol = " "
style = "fg:sapphire"
format = "[ $symbol$context ]($style)"

[kubernetes]
disabled = false
symbol = "󱃾 "
style = "fg:lavender"
format = "[ $symbol$context ]($style)"

[fill]
symbol = " "

[cmd_duration]
min_time = 2_000
style = "fg:overlay1"
format = "[$duration ]($style)"

[time]
disabled = true

[line_break]
disabled = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](mauve)"

[palettes.dusk]
rosewater = "#FCE4DE"
flamingo = "#F2BFB4"
pink = "#F3BDCA"
mauve = "#C4A2D4"
red = "#E27878"
maroon = "#E09898"
peach = "#DDA05C"
yellow = "#DEC47C"
green = "#82C8A0"
teal = "#6EC4B8"
sky = "#75D6F6"
sapphire = "#5CB8E4"
blue = "#68ACE0"
lavender = "#B0BCE8"
text = "#F3F5FC"
subtext1 = "#D2D5DE"
subtext0 = "#B2B6C1"
overlay2 = "#8F939F"
overlay1 = "#7E828F"
overlay0 = "#6E7280"
surface2 = "#60646E"
surface1 = "#52565F"
surface0 = "#454850"
base = "#393C43"
mantle = "#2F3238"
crust = "#26282D"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
