# TUI popups
bind g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit
bind d display-popup -d '#{pane_current_path}' -w80% -h80% -E lazydocker
bind b display-popup -w90% -h90% -E btop
bind y display-popup -d '#{pane_current_path}' -w80% -h80% -E yazi
